"1":
  stage: "1"
  name: "Tìm hiểu đề bài (Let's get this bread, fam!)"
  description: |
    Yo! Chào mừng đến với buổi luyện toán chất như nước cất. Hôm nay, chúng ta sẽ flex skill với bài toán xét tính đơn điệu của hàm số. Nghe có vẻ căng thẳng, nhưng đừng lo, tụi mình sẽ cùng nhau rap giải bài này!
    Đầu tiên, đọc kỹ đề bài và xác định mục tiêu của chúng ta là gì nhé. Đề bài đang hỏi gì?
  tasks:
    - id: "1.1"
      description: |
        Alright, cho mình biết đề bài yêu cầu làm gì nào? Nói nôm na là chúng ta cần chứng minh hay tìm cái gì?
        (Gợi ý: Đề bài đang hỏi về sự tăng giảm của hàm số, đúng không?)
    - id: "1.2"
      description: |
        Có những thuật ngữ toán học nào mà bạn thấy quen thuộc trong đề bài này? (Ví dụ: hàm số, đơn điệu,...)
        Hiểu rõ mấy thuật ngữ này là chìa khóa để mình mở cánh cửa bài toán đó nha!
  goals:
    - "Hiểu rõ yêu cầu bài toán: Xét tính đơn điệu của hàm số."
    - "Nhận diện các thuật ngữ liên quan: Hàm số, tính đơn điệu (đồng biến, nghịch biến)."

"2":
  stage: "2"
  name: "Lập kế hoạch giải bài (Time to make a plan, G!)"
  description: |
    Giờ là lúc tụi mình brainstorm để vạch ra một chiến lược giải bài đỉnh của chóp!
    Hãy nhớ lại những kiến thức đã học về tính đơn điệu của hàm số. Cần những bước nào để chứng minh nó?
  tasks:
    - id: "2.1"
      description: |
        Để xét tính đơn điệu của hàm số, chúng ta thường làm những bước gì? (Gợi ý: Tìm tập xác định, tính đạo hàm,...)
        Hãy liệt kê các bước đó ra để có cái nhìn tổng quan trước khi "chiến" nha!
    - id: "2.2"
      description: |
        Công cụ quan trọng nhất để xét tính đơn điệu là gì? (Gợi ý: Liên quan đến đạo hàm đó nha!)
        Đạo hàm có mối liên hệ như thế nào với sự đồng biến và nghịch biến của hàm số?
  goals:
    - "Xác định các bước cần thiết để giải bài toán: Tìm TXĐ, tính đạo hàm, xét dấu đạo hàm, lập BBT, kết luận."
    - "Nhớ lại mối liên hệ giữa đạo hàm và tính đơn điệu của hàm số."

"3":
  stage: "3"
  name: "Thực hiện giải bài (Let's do this! No cap!)"
  description: |
    Okay, đến lúc thực chiến rồi đây! Bắt đầu từ bước đầu tiên trong kế hoạch của chúng ta.
    Nhớ là cứ bình tĩnh mà "quẩy" thôi nha!
  tasks:
    - id: "3.1"
      description: |
        Bước đầu tiên là gì nhỉ? (Gợi ý: Xem hàm số có "khó ở" chỗ nào không, tức là tìm điều kiện xác định).
        Hãy tìm tập xác định của hàm số $f(x) = x^3 + 3x + 1$.
        Hàm số này có điều kiện gì không?
    - id: "3.2"
      description: |
        Tiếp theo, chúng ta cần "bắt" cái gì của hàm số này? (Gợi ý: Nó giúp ta biết hàm số đang "lên" hay "xuống" đó).
        Chính xác! Hãy tính đạo hàm $f'(x)$ của hàm số $f(x) = x^3 + 3x + 1$.
        Nhớ lại công thức đạo hàm của $x^n$ là gì nào?
    - id: "3.3"
      description: |
        Sau khi tính đạo hàm, bước quan trọng tiếp theo là gì? (Gợi ý: Xem nó âm hay dương).
        Hãy xét dấu của đạo hàm $f'(x) = 3x^2 + 3$.
        $f'(x)$ luôn dương, luôn âm, hay có lúc âm lúc dương? Vì sao?
    - id: "3.4"
      description: |
        Với đạo hàm luôn dương (hoặc luôn âm), ta có thể suy ra điều gì về sự biến thiên của hàm số?
        Hàm số $f(x)$ đồng biến hay nghịch biến trên tập xác định?
    - id: "3.5"
      description: |
        Để có cái nhìn trực quan hơn, chúng ta có thể làm gì? (Gợi ý: Kẻ một cái bảng để thấy rõ sự biến thiên).
        Hãy phác thảo bảng biến thiên của hàm số $f(x)$. Ghi rõ chiều biến thiên (mũi tên lên hay xuống).
  goals:
    - "Tìm tập xác định của hàm số."
    - "Tính đạo hàm của hàm số."
    - "Xét dấu đạo hàm và kết luận về tính đơn điệu."
    - "Lập bảng biến thiên để trực quan hóa kết quả."

"4":
  stage: "4"
  name: "Kết luận và Đánh giá (Mic drop! We did it!)"
  description: |
    Yeah! Vậy là chúng ta đã "cân" xong bài toán này rồi đó!
    Bây giờ, hãy tóm tắt lại kết quả và rút ra kết luận cuối cùng.
  tasks:
    - id: "4.1"
      description: |
        Dựa vào các bước đã làm, bạn hãy đưa ra kết luận về tính đơn điệu của hàm số $f(x) = x^3 + 3x + 1$.
        Hàm số này đồng biến, nghịch biến, hay không đổi trên tập xác định?
    - id: "4.2"
      description: |
        Bạn có thể giải thích tại sao hàm số lại có tính đơn điệu như vậy không? (Dựa vào dấu của đạo hàm).
        Hãy tóm tắt lại quá trình giải bài để hiểu rõ hơn nhé!
  goals:
    - "Đưa ra kết luận chính xác về tính đơn điệu của hàm số."
    - "Giải thích được lý do hàm số có tính đơn điệu đó."
    - "Ôn lại các bước giải và nắm vững kiến thức."